<a href="https://colab.research.google.com/github/Ashutosh4328/Infosys_springboard-6.0/blob/main/Ashutosh_Infosys_SkillMatch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python NumPy**

In [27]:
import numpy as np
n1=np.array([10,20,30,40])

print(n1)

[10 20 30 40]


In [29]:
import numpy as np
n2=np.array([[10,20,30,40],[40,30,20,10]])
print(n2)

[[10 20 30 40]
 [40 30 20 10]]


In [31]:
import numpy as np
n3=np.zeros((1,2))
print(n1)

[10 20 30 40]


In [34]:
import numpy as np
n1=np.zeros((2,2), dtype=int)
n1

array([[0, 0],
       [0, 0]])

In [35]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
import numpy as np
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [37]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [38]:
import numpy as np
n2=np.array([[10,20,30,40,],[40,30,20,10,]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [39]:
import numpy as np
n1=np.random.randint(1,100,5)
n1

array([64, 23, 83, 28,  1])

In [40]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,3,2,1])
np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [41]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,3,2,1])
np.hstack((n1,n2))

array([1, 2, 3, 4, 4, 3, 2, 1])

In [42]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,3,2,1])
np.column_stack((n1,n2))

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [43]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,3,2,1])
np.sum((n1,n2))

np.int64(20)

In [44]:
import numpy as np
n1=np.array([10,20,30,40])
np.mean(n1)

np.float64(25.0)

In [45]:
import numpy as np
n1=np.array([10,20,30,40])
np.std(n1)

np.float64(11.180339887498949)

In [46]:
import numpy as np
n1=np.array([10,20,30,40])
np.median(n1)

np.float64(25.0)

In [47]:
n1

array([10, 20, 30, 40])

In [48]:
n1.transpose()

array([10, 20, 30, 40])

**Pandas** 🐼

In [49]:
import pandas as pd

s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [50]:
import pandas as pd

s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
s1+s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [51]:
import pandas as pd
pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]})


Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

In [1]:
import pandas as pd
ds=pd.read_csv("/content/iris.csv")

In [2]:
ds.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
ds.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [5]:
ds.shape

(150, 5)

In [6]:
ds.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

from matplotlib import pyplot as plt
_df_0['sepal_length'].plot(kind='hist', bins=20, title='sepal_length')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['sepal_width'].plot(kind='hist', bins=20, title='sepal_width')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['petal_length'].plot(kind='hist', bins=20, title='petal_length')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['petal_width'].plot(kind='hist', bins=20, title='petal_width')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('index').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='sepal_length', y='sepal_width', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='sepal_width', y='petal_length', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='petal_length', y='petal_width', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['sepal_length'].plot(kind='line', figsize=(8, 4), title='sepal_length')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['sepal_width'].plot(kind='line', figsize=(8, 4), title='sepal_width')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['petal_length'].plot(kind='line', figsize=(8, 4), title='petal_length')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['petal_width'].plot(kind='line', figsize=(8, 4), title='petal_width')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_12['index'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_12, x='sepal_length', y='index', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['index'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='sepal_width', y='index', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['index'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='petal_length', y='index', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['index'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='petal_width', y='index', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [8]:
ds.loc[10:20, ["sepal_width"]]

sepal_width
10          3.7
11          3.4
12          3.0
13          3.0
14          4.0
15          4.4
16          3.9
17          3.5
18          3.8
19          3.8
20          3.4

In [10]:
ds.iloc[0:3,0:2]

sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

In [12]:
ds.drop([1,2,3],axis=0)

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [14]:
ds.drop("sepal_length", axis=1)

sepal_width  petal_length  petal_width    species
0            3.5           1.4          0.2     setosa
1            3.0           1.4          0.2     setosa
2            3.2           1.3          0.2     setosa
3            3.1           1.5          0.2     setosa
4            3.6           1.4          0.2     setosa
..           ...           ...          ...        ...
145          3.0           5.2          2.3  virginica
146          2.5           5.0          1.9  virginica
147          3.0           5.2          2.0  virginica
148          3.4           5.4          2.3  virginica
149          3.0           5.1          1.8  virginica

[150 rows x 4 columns]

In [19]:
ds.mean(numeric_only=True)

sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64

In [20]:
ds.min(numeric_only=True)

sepal_length    4.3
sepal_width     2.0
petal_length    1.0
petal_width     0.1
dtype: float64

In [22]:
ds.median(numeric_only=True)

sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [24]:
ds.max(numeric_only=True)

sepal_length    7.9
sepal_width     4.4
petal_length    6.9
petal_width     2.5
dtype: float64